[package]
name = "barebones"
version = "0.1.0"
edition = "2021"

[dependencies]
volatile = "0.2.6"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"
bitflags = "1.3"

[profile.release]
panic = "abort"
#strip = true  # Automatically strip symbols from the binary.